title: n30 # name of the site
author: n30 # name of site's author
email: ereymundo2013@gmail.com # email of site's author
url: https://ericlikedis.github.io # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if your site shouldn't use a subpath)
description: >
  <p><span style="color: #FFFFFF; font-size: 1.2em;">ἀτμίς</span> <br> my only fixed address.. <br> i take photos sometimes, i study cyber (MSCIA). certified yearner. S tier outfit repeater. go to work for 2 hours then come home and log off for the rest of the day enjoyer. <a href="https://open.spotify.com/user/nerdyfresh08?si=59ea43b02e91442c" style="color: #FFFFFF;"> <span style="color: #FFFFFF;"> <br>  <br> ► listen to my spotify playlists! ◄ <br> <br> </span> </a> <span style="color: #0ed200;"> interest: privacy & security, dog walking, art history, philosophy, music, writing, books, photography, experiencing things, learning... <br> <br> dislikes: red pill content, advertising, 2-factor authentication, and proprietary software.<br> <p>

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  reco:
    output: true

terminal_lines:
  - "$ scanning local network..."
  - "$ authenticating..."
  - "$ status: ok!"
# optional: per-line delay (in milliseconds)
terminal_char_ms: 90  # ms per character (matches --t above)
terminal_gap_ms: 600   # pause between lines